# syntax=docker/dockerfile:1
ARG GO_VERSION=1.27.0
FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG TARGETOS
ARG TARGETARCH
ARG VERSION=dev
ARG COMMIT=unknown
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -trimpath -ldflags "-s -w" -o /out/endlessnet-relay ./cmd/endlessnet-relay

FROM gcr.io/distroless/static-debian13:nonroot
COPY --from=build /out/endlessnet-relay /usr/local/bin/endlessnet-relay
USER 65532:65532
EXPOSE 9443 9444 9090
ENTRYPOINT ["/usr/local/bin/endlessnet-relay"]
