// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: api/relay/v1/relay.proto

package relayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayControl_RegisterInstance_FullMethodName  = "/endlessnet.relay.v1.RelayControl/RegisterInstance"
	RelayControl_HeartbeatInstance_FullMethodName = "/endlessnet.relay.v1.RelayControl/HeartbeatInstance"
	RelayControl_AcquireSession_FullMethodName    = "/endlessnet.relay.v1.RelayControl/AcquireSession"
	RelayControl_RenewSession_FullMethodName      = "/endlessnet.relay.v1.RelayControl/RenewSession"
	RelayControl_ReleaseSession_FullMethodName    = "/endlessnet.relay.v1.RelayControl/ReleaseSession"
	RelayControl_AuthorizePeer_FullMethodName     = "/endlessnet.relay.v1.RelayControl/AuthorizePeer"
)

// RelayControlClient is the client API for RelayControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayControlClient interface {
	RegisterInstance(ctx context.Context, in *RegisterInstanceRequest, opts ...grpc.CallOption) (*RegisterInstanceResponse, error)
	HeartbeatInstance(ctx context.Context, in *HeartbeatInstanceRequest, opts ...grpc.CallOption) (*HeartbeatInstanceResponse, error)
	AcquireSession(ctx context.Context, in *AcquireSessionRequest, opts ...grpc.CallOption) (*AcquireSessionResponse, error)
	RenewSession(ctx context.Context, in *RenewSessionRequest, opts ...grpc.CallOption) (*RenewSessionResponse, error)
	ReleaseSession(ctx context.Context, in *ReleaseSessionRequest, opts ...grpc.CallOption) (*ReleaseSessionResponse, error)
	AuthorizePeer(ctx context.Context, in *AuthorizePeerRequest, opts ...grpc.CallOption) (*AuthorizePeerResponse, error)
}

type relayControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayControlClient(cc grpc.ClientConnInterface) RelayControlClient {
	return &relayControlClient{cc}
}

func (c *relayControlClient) RegisterInstance(ctx context.Context, in *RegisterInstanceRequest, opts ...grpc.CallOption) (*RegisterInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterInstanceResponse)
	err := c.cc.Invoke(ctx, RelayControl_RegisterInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayControlClient) HeartbeatInstance(ctx context.Context, in *HeartbeatInstanceRequest, opts ...grpc.CallOption) (*HeartbeatInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatInstanceResponse)
	err := c.cc.Invoke(ctx, RelayControl_HeartbeatInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayControlClient) AcquireSession(ctx context.Context, in *AcquireSessionRequest, opts ...grpc.CallOption) (*AcquireSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireSessionResponse)
	err := c.cc.Invoke(ctx, RelayControl_AcquireSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayControlClient) RenewSession(ctx context.Context, in *RenewSessionRequest, opts ...grpc.CallOption) (*RenewSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewSessionResponse)
	err := c.cc.Invoke(ctx, RelayControl_RenewSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayControlClient) ReleaseSession(ctx context.Context, in *ReleaseSessionRequest, opts ...grpc.CallOption) (*ReleaseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSessionResponse)
	err := c.cc.Invoke(ctx, RelayControl_ReleaseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayControlClient) AuthorizePeer(ctx context.Context, in *AuthorizePeerRequest, opts ...grpc.CallOption) (*AuthorizePeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizePeerResponse)
	err := c.cc.Invoke(ctx, RelayControl_AuthorizePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayControlServer is the server API for RelayControl service.
// All implementations must embed UnimplementedRelayControlServer
// for forward compatibility.
type RelayControlServer interface {
	RegisterInstance(context.Context, *RegisterInstanceRequest) (*RegisterInstanceResponse, error)
	HeartbeatInstance(context.Context, *HeartbeatInstanceRequest) (*HeartbeatInstanceResponse, error)
	AcquireSession(context.Context, *AcquireSessionRequest) (*AcquireSessionResponse, error)
	RenewSession(context.Context, *RenewSessionRequest) (*RenewSessionResponse, error)
	ReleaseSession(context.Context, *ReleaseSessionRequest) (*ReleaseSessionResponse, error)
	AuthorizePeer(context.Context, *AuthorizePeerRequest) (*AuthorizePeerResponse, error)
	mustEmbedUnimplementedRelayControlServer()
}

// UnimplementedRelayControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayControlServer struct{}

func (UnimplementedRelayControlServer) RegisterInstance(context.Context, *RegisterInstanceRequest) (*RegisterInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterInstance not implemented")
}
func (UnimplementedRelayControlServer) HeartbeatInstance(context.Context, *HeartbeatInstanceRequest) (*HeartbeatInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatInstance not implemented")
}
func (UnimplementedRelayControlServer) AcquireSession(context.Context, *AcquireSessionRequest) (*AcquireSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireSession not implemented")
}
func (UnimplementedRelayControlServer) RenewSession(context.Context, *RenewSessionRequest) (*RenewSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewSession not implemented")
}
func (UnimplementedRelayControlServer) ReleaseSession(context.Context, *ReleaseSessionRequest) (*ReleaseSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseSession not implemented")
}
func (UnimplementedRelayControlServer) AuthorizePeer(context.Context, *AuthorizePeerRequest) (*AuthorizePeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizePeer not implemented")
}
func (UnimplementedRelayControlServer) mustEmbedUnimplementedRelayControlServer() {}
func (UnimplementedRelayControlServer) testEmbeddedByValue()                      {}

// UnsafeRelayControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayControlServer will
// result in compilation errors.
type UnsafeRelayControlServer interface {
	mustEmbedUnimplementedRelayControlServer()
}

func RegisterRelayControlServer(s grpc.ServiceRegistrar, srv RelayControlServer) {
	// If the following call pancis, it indicates UnimplementedRelayControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayControl_ServiceDesc, srv)
}

func _RelayControl_RegisterInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).RegisterInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_RegisterInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).RegisterInstance(ctx, req.(*RegisterInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayControl_HeartbeatInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).HeartbeatInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_HeartbeatInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).HeartbeatInstance(ctx, req.(*HeartbeatInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayControl_AcquireSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).AcquireSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_AcquireSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).AcquireSession(ctx, req.(*AcquireSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayControl_RenewSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).RenewSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_RenewSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).RenewSession(ctx, req.(*RenewSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayControl_ReleaseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).ReleaseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_ReleaseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).ReleaseSession(ctx, req.(*ReleaseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayControl_AuthorizePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).AuthorizePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_AuthorizePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).AuthorizePeer(ctx, req.(*AuthorizePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayControl_ServiceDesc is the grpc.ServiceDesc for RelayControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "endlessnet.relay.v1.RelayControl",
	HandlerType: (*RelayControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterInstance",
			Handler:    _RelayControl_RegisterInstance_Handler,
		},
		{
			MethodName: "HeartbeatInstance",
			Handler:    _RelayControl_HeartbeatInstance_Handler,
		},
		{
			MethodName: "AcquireSession",
			Handler:    _RelayControl_AcquireSession_Handler,
		},
		{
			MethodName: "RenewSession",
			Handler:    _RelayControl_RenewSession_Handler,
		},
		{
			MethodName: "ReleaseSession",
			Handler:    _RelayControl_ReleaseSession_Handler,
		},
		{
			MethodName: "AuthorizePeer",
			Handler:    _RelayControl_AuthorizePeer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/relay/v1/relay.proto",
}

const (
	RelayMesh_Connect_FullMethodName = "/endlessnet.relay.v1.RelayMesh/Connect"
)

// RelayMeshClient is the client API for RelayMesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayMeshClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MeshMessage, MeshMessage], error)
}

type relayMeshClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayMeshClient(cc grpc.ClientConnInterface) RelayMeshClient {
	return &relayMeshClient{cc}
}

func (c *relayMeshClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MeshMessage, MeshMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RelayMesh_ServiceDesc.Streams[0], RelayMesh_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MeshMessage, MeshMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RelayMesh_ConnectClient = grpc.BidiStreamingClient[MeshMessage, MeshMessage]

// RelayMeshServer is the server API for RelayMesh service.
// All implementations must embed UnimplementedRelayMeshServer
// for forward compatibility.
type RelayMeshServer interface {
	Connect(grpc.BidiStreamingServer[MeshMessage, MeshMessage]) error
	mustEmbedUnimplementedRelayMeshServer()
}

// UnimplementedRelayMeshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayMeshServer struct{}

func (UnimplementedRelayMeshServer) Connect(grpc.BidiStreamingServer[MeshMessage, MeshMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRelayMeshServer) mustEmbedUnimplementedRelayMeshServer() {}
func (UnimplementedRelayMeshServer) testEmbeddedByValue()                   {}

// UnsafeRelayMeshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayMeshServer will
// result in compilation errors.
type UnsafeRelayMeshServer interface {
	mustEmbedUnimplementedRelayMeshServer()
}

func RegisterRelayMeshServer(s grpc.ServiceRegistrar, srv RelayMeshServer) {
	// If the following call pancis, it indicates UnimplementedRelayMeshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayMesh_ServiceDesc, srv)
}

func _RelayMesh_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RelayMeshServer).Connect(&grpc.GenericServerStream[MeshMessage, MeshMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RelayMesh_ConnectServer = grpc.BidiStreamingServer[MeshMessage, MeshMessage]

// RelayMesh_ServiceDesc is the grpc.ServiceDesc for RelayMesh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayMesh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "endlessnet.relay.v1.RelayMesh",
	HandlerType: (*RelayMeshServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _RelayMesh_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/relay/v1/relay.proto",
}
