// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/relay/v1/relay.proto

package relayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credential struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Algorithm         string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	KeyId             string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	NetworkId         string                 `protobuf:"bytes,3,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	NodeId            string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ExpiresAtUnixNano int64                  `protobuf:"varint,5,opt,name=expires_at_unix_nano,json=expiresAtUnixNano,proto3" json:"expires_at_unix_nano,omitempty"`
	Signature         string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *Credential) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *Credential) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Credential) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *Credential) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Credential) GetExpiresAtUnixNano() int64 {
	if x != nil {
		return x.ExpiresAtUnixNano
	}
	return 0
}

func (x *Credential) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type SigningTrustKey struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	KeyId             string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm         string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	PublicKey         string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	NotBeforeUnixNano int64                  `protobuf:"varint,4,opt,name=not_before_unix_nano,json=notBeforeUnixNano,proto3" json:"not_before_unix_nano,omitempty"`
	NotAfterUnixNano  int64                  `protobuf:"varint,5,opt,name=not_after_unix_nano,json=notAfterUnixNano,proto3" json:"not_after_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SigningTrustKey) Reset() {
	*x = SigningTrustKey{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningTrustKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningTrustKey) ProtoMessage() {}

func (x *SigningTrustKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningTrustKey.ProtoReflect.Descriptor instead.
func (*SigningTrustKey) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *SigningTrustKey) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SigningTrustKey) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *SigningTrustKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SigningTrustKey) GetNotBeforeUnixNano() int64 {
	if x != nil {
		return x.NotBeforeUnixNano
	}
	return 0
}

func (x *SigningTrustKey) GetNotAfterUnixNano() int64 {
	if x != nil {
		return x.NotAfterUnixNano
	}
	return 0
}

type SigningTrustBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ActiveKeyId   string                 `protobuf:"bytes,2,opt,name=active_key_id,json=activeKeyId,proto3" json:"active_key_id,omitempty"`
	Keys          []*SigningTrustKey     `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningTrustBundle) Reset() {
	*x = SigningTrustBundle{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningTrustBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningTrustBundle) ProtoMessage() {}

func (x *SigningTrustBundle) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningTrustBundle.ProtoReflect.Descriptor instead.
func (*SigningTrustBundle) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *SigningTrustBundle) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SigningTrustBundle) GetActiveKeyId() string {
	if x != nil {
		return x.ActiveKeyId
	}
	return ""
}

func (x *SigningTrustBundle) GetKeys() []*SigningTrustKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type RelayInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayId       string                 `protobuf:"bytes,1,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	BootId        string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	MeshAddr      string                 `protobuf:"bytes,3,opt,name=mesh_addr,json=meshAddr,proto3" json:"mesh_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayInstance) Reset() {
	*x = RelayInstance{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayInstance) ProtoMessage() {}

func (x *RelayInstance) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayInstance.ProtoReflect.Descriptor instead.
func (*RelayInstance) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *RelayInstance) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *RelayInstance) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *RelayInstance) GetMeshAddr() string {
	if x != nil {
		return x.MeshAddr
	}
	return ""
}

type RegisterInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayId       string                 `protobuf:"bytes,1,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	BootId        string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	MeshAddr      string                 `protobuf:"bytes,3,opt,name=mesh_addr,json=meshAddr,proto3" json:"mesh_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInstanceRequest) Reset() {
	*x = RegisterInstanceRequest{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInstanceRequest) ProtoMessage() {}

func (x *RegisterInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInstanceRequest.ProtoReflect.Descriptor instead.
func (*RegisterInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterInstanceRequest) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *RegisterInstanceRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *RegisterInstanceRequest) GetMeshAddr() string {
	if x != nil {
		return x.MeshAddr
	}
	return ""
}

type RegisterInstanceResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Peers                []*RelayInstance       `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	LeaseExpiresUnixNano int64                  `protobuf:"varint,2,opt,name=lease_expires_unix_nano,json=leaseExpiresUnixNano,proto3" json:"lease_expires_unix_nano,omitempty"`
	RelayTrustBundle     *SigningTrustBundle    `protobuf:"bytes,3,opt,name=relay_trust_bundle,json=relayTrustBundle,proto3" json:"relay_trust_bundle,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterInstanceResponse) Reset() {
	*x = RegisterInstanceResponse{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInstanceResponse) ProtoMessage() {}

func (x *RegisterInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInstanceResponse.ProtoReflect.Descriptor instead.
func (*RegisterInstanceResponse) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterInstanceResponse) GetPeers() []*RelayInstance {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *RegisterInstanceResponse) GetLeaseExpiresUnixNano() int64 {
	if x != nil {
		return x.LeaseExpiresUnixNano
	}
	return 0
}

func (x *RegisterInstanceResponse) GetRelayTrustBundle() *SigningTrustBundle {
	if x != nil {
		return x.RelayTrustBundle
	}
	return nil
}

type HeartbeatInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayId       string                 `protobuf:"bytes,1,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	BootId        string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatInstanceRequest) Reset() {
	*x = HeartbeatInstanceRequest{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatInstanceRequest) ProtoMessage() {}

func (x *HeartbeatInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatInstanceRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatInstanceRequest) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *HeartbeatInstanceRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

type HeartbeatInstanceResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Peers                []*RelayInstance       `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	LeaseExpiresUnixNano int64                  `protobuf:"varint,2,opt,name=lease_expires_unix_nano,json=leaseExpiresUnixNano,proto3" json:"lease_expires_unix_nano,omitempty"`
	RelayTrustBundle     *SigningTrustBundle    `protobuf:"bytes,3,opt,name=relay_trust_bundle,json=relayTrustBundle,proto3" json:"relay_trust_bundle,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HeartbeatInstanceResponse) Reset() {
	*x = HeartbeatInstanceResponse{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatInstanceResponse) ProtoMessage() {}

func (x *HeartbeatInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatInstanceResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatInstanceResponse) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatInstanceResponse) GetPeers() []*RelayInstance {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *HeartbeatInstanceResponse) GetLeaseExpiresUnixNano() int64 {
	if x != nil {
		return x.LeaseExpiresUnixNano
	}
	return 0
}

func (x *HeartbeatInstanceResponse) GetRelayTrustBundle() *SigningTrustBundle {
	if x != nil {
		return x.RelayTrustBundle
	}
	return nil
}

type AcquireSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayId       string                 `protobuf:"bytes,1,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	BootId        string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Credential    *Credential            `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireSessionRequest) Reset() {
	*x = AcquireSessionRequest{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireSessionRequest) ProtoMessage() {}

func (x *AcquireSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireSessionRequest.ProtoReflect.Descriptor instead.
func (*AcquireSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{8}
}

func (x *AcquireSessionRequest) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *AcquireSessionRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *AcquireSessionRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type AcquireSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireSessionResponse) Reset() {
	*x = AcquireSessionResponse{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireSessionResponse) ProtoMessage() {}

func (x *AcquireSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireSessionResponse.ProtoReflect.Descriptor instead.
func (*AcquireSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{9}
}

func (x *AcquireSessionResponse) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type RenewSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayId       string                 `protobuf:"bytes,1,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	BootId        string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	NetworkId     string                 `protobuf:"bytes,3,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Credential    *Credential            `protobuf:"bytes,6,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewSessionRequest) Reset() {
	*x = RenewSessionRequest{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewSessionRequest) ProtoMessage() {}

func (x *RenewSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewSessionRequest.ProtoReflect.Descriptor instead.
func (*RenewSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{10}
}

func (x *RenewSessionRequest) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *RenewSessionRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *RenewSessionRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *RenewSessionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RenewSessionRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RenewSessionRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type RenewSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewSessionResponse) Reset() {
	*x = RenewSessionResponse{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewSessionResponse) ProtoMessage() {}

func (x *RenewSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewSessionResponse.ProtoReflect.Descriptor instead.
func (*RenewSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{11}
}

type ReleaseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayId       string                 `protobuf:"bytes,1,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	BootId        string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	NetworkId     string                 `protobuf:"bytes,3,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionRequest) Reset() {
	*x = ReleaseSessionRequest{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionRequest) ProtoMessage() {}

func (x *ReleaseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{12}
}

func (x *ReleaseSessionRequest) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *ReleaseSessionRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *ReleaseSessionRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *ReleaseSessionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReleaseSessionRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type ReleaseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionResponse) Reset() {
	*x = ReleaseSessionResponse{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionResponse) ProtoMessage() {}

func (x *ReleaseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{13}
}

type AuthorizePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayId       string                 `protobuf:"bytes,1,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	BootId        string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Credential    *Credential            `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	PeerId        string                 `protobuf:"bytes,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	SourceEpoch   int64                  `protobuf:"varint,5,opt,name=source_epoch,json=sourceEpoch,proto3" json:"source_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizePeerRequest) Reset() {
	*x = AuthorizePeerRequest{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePeerRequest) ProtoMessage() {}

func (x *AuthorizePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePeerRequest.ProtoReflect.Descriptor instead.
func (*AuthorizePeerRequest) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{14}
}

func (x *AuthorizePeerRequest) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *AuthorizePeerRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *AuthorizePeerRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *AuthorizePeerRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *AuthorizePeerRequest) GetSourceEpoch() int64 {
	if x != nil {
		return x.SourceEpoch
	}
	return 0
}

type AuthorizePeerResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DestinationRelayId string                 `protobuf:"bytes,1,opt,name=destination_relay_id,json=destinationRelayId,proto3" json:"destination_relay_id,omitempty"`
	DestinationBootId  string                 `protobuf:"bytes,2,opt,name=destination_boot_id,json=destinationBootId,proto3" json:"destination_boot_id,omitempty"`
	DestinationEpoch   int64                  `protobuf:"varint,3,opt,name=destination_epoch,json=destinationEpoch,proto3" json:"destination_epoch,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuthorizePeerResponse) Reset() {
	*x = AuthorizePeerResponse{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePeerResponse) ProtoMessage() {}

func (x *AuthorizePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePeerResponse.ProtoReflect.Descriptor instead.
func (*AuthorizePeerResponse) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{15}
}

func (x *AuthorizePeerResponse) GetDestinationRelayId() string {
	if x != nil {
		return x.DestinationRelayId
	}
	return ""
}

func (x *AuthorizePeerResponse) GetDestinationBootId() string {
	if x != nil {
		return x.DestinationBootId
	}
	return ""
}

func (x *AuthorizePeerResponse) GetDestinationEpoch() int64 {
	if x != nil {
		return x.DestinationEpoch
	}
	return 0
}

type MeshMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion int32                  `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*MeshMessage_Hello
	//	*MeshMessage_Frame
	//	*MeshMessage_Ping
	//	*MeshMessage_Pong
	Body          isMeshMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshMessage) Reset() {
	*x = MeshMessage{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshMessage) ProtoMessage() {}

func (x *MeshMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshMessage.ProtoReflect.Descriptor instead.
func (*MeshMessage) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{16}
}

func (x *MeshMessage) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *MeshMessage) GetBody() isMeshMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MeshMessage) GetHello() *MeshHello {
	if x != nil {
		if x, ok := x.Body.(*MeshMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *MeshMessage) GetFrame() *MeshFrame {
	if x != nil {
		if x, ok := x.Body.(*MeshMessage_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

func (x *MeshMessage) GetPing() *MeshPing {
	if x != nil {
		if x, ok := x.Body.(*MeshMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *MeshMessage) GetPong() *MeshPong {
	if x != nil {
		if x, ok := x.Body.(*MeshMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isMeshMessage_Body interface {
	isMeshMessage_Body()
}

type MeshMessage_Hello struct {
	Hello *MeshHello `protobuf:"bytes,2,opt,name=hello,proto3,oneof"`
}

type MeshMessage_Frame struct {
	Frame *MeshFrame `protobuf:"bytes,3,opt,name=frame,proto3,oneof"`
}

type MeshMessage_Ping struct {
	Ping *MeshPing `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

type MeshMessage_Pong struct {
	Pong *MeshPong `protobuf:"bytes,5,opt,name=pong,proto3,oneof"`
}

func (*MeshMessage_Hello) isMeshMessage_Body() {}

func (*MeshMessage_Frame) isMeshMessage_Body() {}

func (*MeshMessage_Ping) isMeshMessage_Body() {}

func (*MeshMessage_Pong) isMeshMessage_Body() {}

type MeshHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayId       string                 `protobuf:"bytes,1,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	BootId        string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshHello) Reset() {
	*x = MeshHello{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshHello) ProtoMessage() {}

func (x *MeshHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshHello.ProtoReflect.Descriptor instead.
func (*MeshHello) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{17}
}

func (x *MeshHello) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *MeshHello) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

type MeshFrame struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RelayId          string                 `protobuf:"bytes,1,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	BootId           string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	NetworkId        string                 `protobuf:"bytes,3,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	FromNodeId       string                 `protobuf:"bytes,4,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	ToNodeId         string                 `protobuf:"bytes,5,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	DestinationEpoch int64                  `protobuf:"varint,6,opt,name=destination_epoch,json=destinationEpoch,proto3" json:"destination_epoch,omitempty"`
	Payload          []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MeshFrame) Reset() {
	*x = MeshFrame{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshFrame) ProtoMessage() {}

func (x *MeshFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshFrame.ProtoReflect.Descriptor instead.
func (*MeshFrame) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{18}
}

func (x *MeshFrame) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *MeshFrame) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *MeshFrame) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *MeshFrame) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *MeshFrame) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

func (x *MeshFrame) GetDestinationEpoch() int64 {
	if x != nil {
		return x.DestinationEpoch
	}
	return 0
}

func (x *MeshFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MeshPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshPing) Reset() {
	*x = MeshPing{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshPing) ProtoMessage() {}

func (x *MeshPing) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshPing.ProtoReflect.Descriptor instead.
func (*MeshPing) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{19}
}

type MeshPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshPong) Reset() {
	*x = MeshPong{}
	mi := &file_api_relay_v1_relay_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshPong) ProtoMessage() {}

func (x *MeshPong) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_relay_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshPong.ProtoReflect.Descriptor instead.
func (*MeshPong) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_relay_proto_rawDescGZIP(), []int{20}
}

var File_api_relay_v1_relay_proto protoreflect.FileDescriptor

const file_api_relay_v1_relay_proto_rawDesc = "" +
	"\n" +
	"\x18api/relay/v1/relay.proto\x12\x13endlessnet.relay.v1\"\xc8\x01\n" +
	"\n" +
	"Credential\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x03 \x01(\tR\tnetworkId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12/\n" +
	"\x14expires_at_unix_nano\x18\x05 \x01(\x03R\x11expiresAtUnixNano\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\"\xc5\x01\n" +
	"\x0fSigningTrustKey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12/\n" +
	"\x14not_before_unix_nano\x18\x04 \x01(\x03R\x11notBeforeUnixNano\x12-\n" +
	"\x13not_after_unix_nano\x18\x05 \x01(\x03R\x10notAfterUnixNano\"\x8c\x01\n" +
	"\x12SigningTrustBundle\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\"\n" +
	"\ractive_key_id\x18\x02 \x01(\tR\vactiveKeyId\x128\n" +
	"\x04keys\x18\x03 \x03(\v2$.endlessnet.relay.v1.SigningTrustKeyR\x04keys\"`\n" +
	"\rRelayInstance\x12\x19\n" +
	"\brelay_id\x18\x01 \x01(\tR\arelayId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12\x1b\n" +
	"\tmesh_addr\x18\x03 \x01(\tR\bmeshAddr\"j\n" +
	"\x17RegisterInstanceRequest\x12\x19\n" +
	"\brelay_id\x18\x01 \x01(\tR\arelayId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12\x1b\n" +
	"\tmesh_addr\x18\x03 \x01(\tR\bmeshAddr\"\xe2\x01\n" +
	"\x18RegisterInstanceResponse\x128\n" +
	"\x05peers\x18\x01 \x03(\v2\".endlessnet.relay.v1.RelayInstanceR\x05peers\x125\n" +
	"\x17lease_expires_unix_nano\x18\x02 \x01(\x03R\x14leaseExpiresUnixNano\x12U\n" +
	"\x12relay_trust_bundle\x18\x03 \x01(\v2'.endlessnet.relay.v1.SigningTrustBundleR\x10relayTrustBundle\"N\n" +
	"\x18HeartbeatInstanceRequest\x12\x19\n" +
	"\brelay_id\x18\x01 \x01(\tR\arelayId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\"\xe3\x01\n" +
	"\x19HeartbeatInstanceResponse\x128\n" +
	"\x05peers\x18\x01 \x03(\v2\".endlessnet.relay.v1.RelayInstanceR\x05peers\x125\n" +
	"\x17lease_expires_unix_nano\x18\x02 \x01(\x03R\x14leaseExpiresUnixNano\x12U\n" +
	"\x12relay_trust_bundle\x18\x03 \x01(\v2'.endlessnet.relay.v1.SigningTrustBundleR\x10relayTrustBundle\"\x8c\x01\n" +
	"\x15AcquireSessionRequest\x12\x19\n" +
	"\brelay_id\x18\x01 \x01(\tR\arelayId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12?\n" +
	"\n" +
	"credential\x18\x03 \x01(\v2\x1f.endlessnet.relay.v1.CredentialR\n" +
	"credential\".\n" +
	"\x16AcquireSessionResponse\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\"\xd8\x01\n" +
	"\x13RenewSessionRequest\x12\x19\n" +
	"\brelay_id\x18\x01 \x01(\tR\arelayId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x03 \x01(\tR\tnetworkId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x03R\x05epoch\x12?\n" +
	"\n" +
	"credential\x18\x06 \x01(\v2\x1f.endlessnet.relay.v1.CredentialR\n" +
	"credential\"\x16\n" +
	"\x14RenewSessionResponse\"\x99\x01\n" +
	"\x15ReleaseSessionRequest\x12\x19\n" +
	"\brelay_id\x18\x01 \x01(\tR\arelayId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x03 \x01(\tR\tnetworkId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x03R\x05epoch\"\x18\n" +
	"\x16ReleaseSessionResponse\"\xc7\x01\n" +
	"\x14AuthorizePeerRequest\x12\x19\n" +
	"\brelay_id\x18\x01 \x01(\tR\arelayId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12?\n" +
	"\n" +
	"credential\x18\x03 \x01(\v2\x1f.endlessnet.relay.v1.CredentialR\n" +
	"credential\x12\x17\n" +
	"\apeer_id\x18\x04 \x01(\tR\x06peerId\x12!\n" +
	"\fsource_epoch\x18\x05 \x01(\x03R\vsourceEpoch\"\xa6\x01\n" +
	"\x15AuthorizePeerResponse\x120\n" +
	"\x14destination_relay_id\x18\x01 \x01(\tR\x12destinationRelayId\x12.\n" +
	"\x13destination_boot_id\x18\x02 \x01(\tR\x11destinationBootId\x12+\n" +
	"\x11destination_epoch\x18\x03 \x01(\x03R\x10destinationEpoch\"\x9a\x02\n" +
	"\vMeshMessage\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\x05R\x0fprotocolVersion\x126\n" +
	"\x05hello\x18\x02 \x01(\v2\x1e.endlessnet.relay.v1.MeshHelloH\x00R\x05hello\x126\n" +
	"\x05frame\x18\x03 \x01(\v2\x1e.endlessnet.relay.v1.MeshFrameH\x00R\x05frame\x123\n" +
	"\x04ping\x18\x04 \x01(\v2\x1d.endlessnet.relay.v1.MeshPingH\x00R\x04ping\x123\n" +
	"\x04pong\x18\x05 \x01(\v2\x1d.endlessnet.relay.v1.MeshPongH\x00R\x04pongB\x06\n" +
	"\x04body\"?\n" +
	"\tMeshHello\x12\x19\n" +
	"\brelay_id\x18\x01 \x01(\tR\arelayId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\"\xe5\x01\n" +
	"\tMeshFrame\x12\x19\n" +
	"\brelay_id\x18\x01 \x01(\tR\arelayId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x03 \x01(\tR\tnetworkId\x12 \n" +
	"\ffrom_node_id\x18\x04 \x01(\tR\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x05 \x01(\tR\btoNodeId\x12+\n" +
	"\x11destination_epoch\x18\x06 \x01(\x03R\x10destinationEpoch\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"\n" +
	"\n" +
	"\bMeshPing\"\n" +
	"\n" +
	"\bMeshPong2\x96\x05\n" +
	"\fRelayControl\x12o\n" +
	"\x10RegisterInstance\x12,.endlessnet.relay.v1.RegisterInstanceRequest\x1a-.endlessnet.relay.v1.RegisterInstanceResponse\x12r\n" +
	"\x11HeartbeatInstance\x12-.endlessnet.relay.v1.HeartbeatInstanceRequest\x1a..endlessnet.relay.v1.HeartbeatInstanceResponse\x12i\n" +
	"\x0eAcquireSession\x12*.endlessnet.relay.v1.AcquireSessionRequest\x1a+.endlessnet.relay.v1.AcquireSessionResponse\x12c\n" +
	"\fRenewSession\x12(.endlessnet.relay.v1.RenewSessionRequest\x1a).endlessnet.relay.v1.RenewSessionResponse\x12i\n" +
	"\x0eReleaseSession\x12*.endlessnet.relay.v1.ReleaseSessionRequest\x1a+.endlessnet.relay.v1.ReleaseSessionResponse\x12f\n" +
	"\rAuthorizePeer\x12).endlessnet.relay.v1.AuthorizePeerRequest\x1a*.endlessnet.relay.v1.AuthorizePeerResponse2^\n" +
	"\tRelayMesh\x12Q\n" +
	"\aConnect\x12 .endlessnet.relay.v1.MeshMessage\x1a .endlessnet.relay.v1.MeshMessage(\x010\x01B3Z1github.com/endless-net/relay/api/relay/v1;relayv1b\x06proto3"

var (
	file_api_relay_v1_relay_proto_rawDescOnce sync.Once
	file_api_relay_v1_relay_proto_rawDescData []byte
)

func file_api_relay_v1_relay_proto_rawDescGZIP() []byte {
	file_api_relay_v1_relay_proto_rawDescOnce.Do(func() {
		file_api_relay_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_relay_v1_relay_proto_rawDesc), len(file_api_relay_v1_relay_proto_rawDesc)))
	})
	return file_api_relay_v1_relay_proto_rawDescData
}

var file_api_relay_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_relay_v1_relay_proto_goTypes = []any{
	(*Credential)(nil),                // 0: endlessnet.relay.v1.Credential
	(*SigningTrustKey)(nil),           // 1: endlessnet.relay.v1.SigningTrustKey
	(*SigningTrustBundle)(nil),        // 2: endlessnet.relay.v1.SigningTrustBundle
	(*RelayInstance)(nil),             // 3: endlessnet.relay.v1.RelayInstance
	(*RegisterInstanceRequest)(nil),   // 4: endlessnet.relay.v1.RegisterInstanceRequest
	(*RegisterInstanceResponse)(nil),  // 5: endlessnet.relay.v1.RegisterInstanceResponse
	(*HeartbeatInstanceRequest)(nil),  // 6: endlessnet.relay.v1.HeartbeatInstanceRequest
	(*HeartbeatInstanceResponse)(nil), // 7: endlessnet.relay.v1.HeartbeatInstanceResponse
	(*AcquireSessionRequest)(nil),     // 8: endlessnet.relay.v1.AcquireSessionRequest
	(*AcquireSessionResponse)(nil),    // 9: endlessnet.relay.v1.AcquireSessionResponse
	(*RenewSessionRequest)(nil),       // 10: endlessnet.relay.v1.RenewSessionRequest
	(*RenewSessionResponse)(nil),      // 11: endlessnet.relay.v1.RenewSessionResponse
	(*ReleaseSessionRequest)(nil),     // 12: endlessnet.relay.v1.ReleaseSessionRequest
	(*ReleaseSessionResponse)(nil),    // 13: endlessnet.relay.v1.ReleaseSessionResponse
	(*AuthorizePeerRequest)(nil),      // 14: endlessnet.relay.v1.AuthorizePeerRequest
	(*AuthorizePeerResponse)(nil),     // 15: endlessnet.relay.v1.AuthorizePeerResponse
	(*MeshMessage)(nil),               // 16: endlessnet.relay.v1.MeshMessage
	(*MeshHello)(nil),                 // 17: endlessnet.relay.v1.MeshHello
	(*MeshFrame)(nil),                 // 18: endlessnet.relay.v1.MeshFrame
	(*MeshPing)(nil),                  // 19: endlessnet.relay.v1.MeshPing
	(*MeshPong)(nil),                  // 20: endlessnet.relay.v1.MeshPong
}
var file_api_relay_v1_relay_proto_depIdxs = []int32{
	1,  // 0: endlessnet.relay.v1.SigningTrustBundle.keys:type_name -> endlessnet.relay.v1.SigningTrustKey
	3,  // 1: endlessnet.relay.v1.RegisterInstanceResponse.peers:type_name -> endlessnet.relay.v1.RelayInstance
	2,  // 2: endlessnet.relay.v1.RegisterInstanceResponse.relay_trust_bundle:type_name -> endlessnet.relay.v1.SigningTrustBundle
	3,  // 3: endlessnet.relay.v1.HeartbeatInstanceResponse.peers:type_name -> endlessnet.relay.v1.RelayInstance
	2,  // 4: endlessnet.relay.v1.HeartbeatInstanceResponse.relay_trust_bundle:type_name -> endlessnet.relay.v1.SigningTrustBundle
	0,  // 5: endlessnet.relay.v1.AcquireSessionRequest.credential:type_name -> endlessnet.relay.v1.Credential
	0,  // 6: endlessnet.relay.v1.RenewSessionRequest.credential:type_name -> endlessnet.relay.v1.Credential
	0,  // 7: endlessnet.relay.v1.AuthorizePeerRequest.credential:type_name -> endlessnet.relay.v1.Credential
	17, // 8: endlessnet.relay.v1.MeshMessage.hello:type_name -> endlessnet.relay.v1.MeshHello
	18, // 9: endlessnet.relay.v1.MeshMessage.frame:type_name -> endlessnet.relay.v1.MeshFrame
	19, // 10: endlessnet.relay.v1.MeshMessage.ping:type_name -> endlessnet.relay.v1.MeshPing
	20, // 11: endlessnet.relay.v1.MeshMessage.pong:type_name -> endlessnet.relay.v1.MeshPong
	4,  // 12: endlessnet.relay.v1.RelayControl.RegisterInstance:input_type -> endlessnet.relay.v1.RegisterInstanceRequest
	6,  // 13: endlessnet.relay.v1.RelayControl.HeartbeatInstance:input_type -> endlessnet.relay.v1.HeartbeatInstanceRequest
	8,  // 14: endlessnet.relay.v1.RelayControl.AcquireSession:input_type -> endlessnet.relay.v1.AcquireSessionRequest
	10, // 15: endlessnet.relay.v1.RelayControl.RenewSession:input_type -> endlessnet.relay.v1.RenewSessionRequest
	12, // 16: endlessnet.relay.v1.RelayControl.ReleaseSession:input_type -> endlessnet.relay.v1.ReleaseSessionRequest
	14, // 17: endlessnet.relay.v1.RelayControl.AuthorizePeer:input_type -> endlessnet.relay.v1.AuthorizePeerRequest
	16, // 18: endlessnet.relay.v1.RelayMesh.Connect:input_type -> endlessnet.relay.v1.MeshMessage
	5,  // 19: endlessnet.relay.v1.RelayControl.RegisterInstance:output_type -> endlessnet.relay.v1.RegisterInstanceResponse
	7,  // 20: endlessnet.relay.v1.RelayControl.HeartbeatInstance:output_type -> endlessnet.relay.v1.HeartbeatInstanceResponse
	9,  // 21: endlessnet.relay.v1.RelayControl.AcquireSession:output_type -> endlessnet.relay.v1.AcquireSessionResponse
	11, // 22: endlessnet.relay.v1.RelayControl.RenewSession:output_type -> endlessnet.relay.v1.RenewSessionResponse
	13, // 23: endlessnet.relay.v1.RelayControl.ReleaseSession:output_type -> endlessnet.relay.v1.ReleaseSessionResponse
	15, // 24: endlessnet.relay.v1.RelayControl.AuthorizePeer:output_type -> endlessnet.relay.v1.AuthorizePeerResponse
	16, // 25: endlessnet.relay.v1.RelayMesh.Connect:output_type -> endlessnet.relay.v1.MeshMessage
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_relay_v1_relay_proto_init() }
func file_api_relay_v1_relay_proto_init() {
	if File_api_relay_v1_relay_proto != nil {
		return
	}
	file_api_relay_v1_relay_proto_msgTypes[16].OneofWrappers = []any{
		(*MeshMessage_Hello)(nil),
		(*MeshMessage_Frame)(nil),
		(*MeshMessage_Ping)(nil),
		(*MeshMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_relay_v1_relay_proto_rawDesc), len(file_api_relay_v1_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_relay_v1_relay_proto_goTypes,
		DependencyIndexes: file_api_relay_v1_relay_proto_depIdxs,
		MessageInfos:      file_api_relay_v1_relay_proto_msgTypes,
	}.Build()
	File_api_relay_v1_relay_proto = out.File
	file_api_relay_v1_relay_proto_goTypes = nil
	file_api_relay_v1_relay_proto_depIdxs = nil
}
