// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/relay/v1/upstream.proto

package relayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayUpstreamService_AuthorizeCredential_FullMethodName = "/endlessnet.relay.v1.RelayUpstreamService/AuthorizeCredential"
	RelayUpstreamService_AuthorizePeerPair_FullMethodName   = "/endlessnet.relay.v1.RelayUpstreamService/AuthorizePeerPair"
	RelayUpstreamService_GetTrustBundle_FullMethodName      = "/endlessnet.relay.v1.RelayUpstreamService/GetTrustBundle"
)

// RelayUpstreamServiceClient is the client API for RelayUpstreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RelayUpstreamService is implemented by the operator's authorization and trust
// authority. Every RPC requires the exact configured Relay Coordinator mTLS identity.
type RelayUpstreamServiceClient interface {
	// OK authorizes the credential; PermissionDenied or Unauthenticated denies it.
	AuthorizeCredential(ctx context.Context, in *AuthorizeCredentialRequest, opts ...grpc.CallOption) (*AuthorizeCredentialResponse, error)
	// Authorization is directional: source credential -> peer_network_id/peer_id.
	// Cross-network pairs require an explicit current upstream permission.
	AuthorizePeerPair(ctx context.Context, in *AuthorizePeerPairRequest, opts ...grpc.CallOption) (*AuthorizePeerPairResponse, error)
	GetTrustBundle(ctx context.Context, in *GetTrustBundleRequest, opts ...grpc.CallOption) (*GetTrustBundleResponse, error)
}

type relayUpstreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayUpstreamServiceClient(cc grpc.ClientConnInterface) RelayUpstreamServiceClient {
	return &relayUpstreamServiceClient{cc}
}

func (c *relayUpstreamServiceClient) AuthorizeCredential(ctx context.Context, in *AuthorizeCredentialRequest, opts ...grpc.CallOption) (*AuthorizeCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeCredentialResponse)
	err := c.cc.Invoke(ctx, RelayUpstreamService_AuthorizeCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayUpstreamServiceClient) AuthorizePeerPair(ctx context.Context, in *AuthorizePeerPairRequest, opts ...grpc.CallOption) (*AuthorizePeerPairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizePeerPairResponse)
	err := c.cc.Invoke(ctx, RelayUpstreamService_AuthorizePeerPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayUpstreamServiceClient) GetTrustBundle(ctx context.Context, in *GetTrustBundleRequest, opts ...grpc.CallOption) (*GetTrustBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrustBundleResponse)
	err := c.cc.Invoke(ctx, RelayUpstreamService_GetTrustBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayUpstreamServiceServer is the server API for RelayUpstreamService service.
// All implementations must embed UnimplementedRelayUpstreamServiceServer
// for forward compatibility.
//
// RelayUpstreamService is implemented by the operator's authorization and trust
// authority. Every RPC requires the exact configured Relay Coordinator mTLS identity.
type RelayUpstreamServiceServer interface {
	// OK authorizes the credential; PermissionDenied or Unauthenticated denies it.
	AuthorizeCredential(context.Context, *AuthorizeCredentialRequest) (*AuthorizeCredentialResponse, error)
	// Authorization is directional: source credential -> peer_network_id/peer_id.
	// Cross-network pairs require an explicit current upstream permission.
	AuthorizePeerPair(context.Context, *AuthorizePeerPairRequest) (*AuthorizePeerPairResponse, error)
	GetTrustBundle(context.Context, *GetTrustBundleRequest) (*GetTrustBundleResponse, error)
	mustEmbedUnimplementedRelayUpstreamServiceServer()
}

// UnimplementedRelayUpstreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayUpstreamServiceServer struct{}

func (UnimplementedRelayUpstreamServiceServer) AuthorizeCredential(context.Context, *AuthorizeCredentialRequest) (*AuthorizeCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeCredential not implemented")
}
func (UnimplementedRelayUpstreamServiceServer) AuthorizePeerPair(context.Context, *AuthorizePeerPairRequest) (*AuthorizePeerPairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizePeerPair not implemented")
}
func (UnimplementedRelayUpstreamServiceServer) GetTrustBundle(context.Context, *GetTrustBundleRequest) (*GetTrustBundleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrustBundle not implemented")
}
func (UnimplementedRelayUpstreamServiceServer) mustEmbedUnimplementedRelayUpstreamServiceServer() {}
func (UnimplementedRelayUpstreamServiceServer) testEmbeddedByValue()                              {}

// UnsafeRelayUpstreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayUpstreamServiceServer will
// result in compilation errors.
type UnsafeRelayUpstreamServiceServer interface {
	mustEmbedUnimplementedRelayUpstreamServiceServer()
}

func RegisterRelayUpstreamServiceServer(s grpc.ServiceRegistrar, srv RelayUpstreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedRelayUpstreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayUpstreamService_ServiceDesc, srv)
}

func _RelayUpstreamService_AuthorizeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayUpstreamServiceServer).AuthorizeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayUpstreamService_AuthorizeCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayUpstreamServiceServer).AuthorizeCredential(ctx, req.(*AuthorizeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayUpstreamService_AuthorizePeerPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizePeerPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayUpstreamServiceServer).AuthorizePeerPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayUpstreamService_AuthorizePeerPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayUpstreamServiceServer).AuthorizePeerPair(ctx, req.(*AuthorizePeerPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayUpstreamService_GetTrustBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrustBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayUpstreamServiceServer).GetTrustBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayUpstreamService_GetTrustBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayUpstreamServiceServer).GetTrustBundle(ctx, req.(*GetTrustBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayUpstreamService_ServiceDesc is the grpc.ServiceDesc for RelayUpstreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayUpstreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "endlessnet.relay.v1.RelayUpstreamService",
	HandlerType: (*RelayUpstreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizeCredential",
			Handler:    _RelayUpstreamService_AuthorizeCredential_Handler,
		},
		{
			MethodName: "AuthorizePeerPair",
			Handler:    _RelayUpstreamService_AuthorizePeerPair_Handler,
		},
		{
			MethodName: "GetTrustBundle",
			Handler:    _RelayUpstreamService_GetTrustBundle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/relay/v1/upstream.proto",
}
