// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/relay/v1/upstream.proto

package relayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeCredentialRequest) Reset() {
	*x = AuthorizeCredentialRequest{}
	mi := &file_api_relay_v1_upstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeCredentialRequest) ProtoMessage() {}

func (x *AuthorizeCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_upstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeCredentialRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeCredentialRequest) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_upstream_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeCredentialRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type AuthorizeCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeCredentialResponse) Reset() {
	*x = AuthorizeCredentialResponse{}
	mi := &file_api_relay_v1_upstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeCredentialResponse) ProtoMessage() {}

func (x *AuthorizeCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_upstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeCredentialResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeCredentialResponse) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_upstream_proto_rawDescGZIP(), []int{1}
}

type AuthorizePeerPairRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Credential *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	PeerId     string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// Required, including when the destination is in the source network.
	PeerNetworkId string `protobuf:"bytes,3,opt,name=peer_network_id,json=peerNetworkId,proto3" json:"peer_network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizePeerPairRequest) Reset() {
	*x = AuthorizePeerPairRequest{}
	mi := &file_api_relay_v1_upstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePeerPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePeerPairRequest) ProtoMessage() {}

func (x *AuthorizePeerPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_upstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePeerPairRequest.ProtoReflect.Descriptor instead.
func (*AuthorizePeerPairRequest) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_upstream_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizePeerPairRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *AuthorizePeerPairRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *AuthorizePeerPairRequest) GetPeerNetworkId() string {
	if x != nil {
		return x.PeerNetworkId
	}
	return ""
}

type AuthorizePeerPairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizePeerPairResponse) Reset() {
	*x = AuthorizePeerPairResponse{}
	mi := &file_api_relay_v1_upstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePeerPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePeerPairResponse) ProtoMessage() {}

func (x *AuthorizePeerPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_upstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePeerPairResponse.ProtoReflect.Descriptor instead.
func (*AuthorizePeerPairResponse) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_upstream_proto_rawDescGZIP(), []int{3}
}

type GetTrustBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrustBundleRequest) Reset() {
	*x = GetTrustBundleRequest{}
	mi := &file_api_relay_v1_upstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrustBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrustBundleRequest) ProtoMessage() {}

func (x *GetTrustBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_upstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrustBundleRequest.ProtoReflect.Descriptor instead.
func (*GetTrustBundleRequest) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_upstream_proto_rawDescGZIP(), []int{4}
}

type GetTrustBundleResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RelayTrustBundle *SigningTrustBundle    `protobuf:"bytes,1,opt,name=relay_trust_bundle,json=relayTrustBundle,proto3" json:"relay_trust_bundle,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTrustBundleResponse) Reset() {
	*x = GetTrustBundleResponse{}
	mi := &file_api_relay_v1_upstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrustBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrustBundleResponse) ProtoMessage() {}

func (x *GetTrustBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_relay_v1_upstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrustBundleResponse.ProtoReflect.Descriptor instead.
func (*GetTrustBundleResponse) Descriptor() ([]byte, []int) {
	return file_api_relay_v1_upstream_proto_rawDescGZIP(), []int{5}
}

func (x *GetTrustBundleResponse) GetRelayTrustBundle() *SigningTrustBundle {
	if x != nil {
		return x.RelayTrustBundle
	}
	return nil
}

var File_api_relay_v1_upstream_proto protoreflect.FileDescriptor

const file_api_relay_v1_upstream_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/relay/v1/upstream.proto\x12\x13endlessnet.relay.v1\x1a\x18api/relay/v1/relay.proto\"]\n" +
	"\x1aAuthorizeCredentialRequest\x12?\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x1f.endlessnet.relay.v1.CredentialR\n" +
	"credential\"\x1d\n" +
	"\x1bAuthorizeCredentialResponse\"\x9c\x01\n" +
	"\x18AuthorizePeerPairRequest\x12?\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x1f.endlessnet.relay.v1.CredentialR\n" +
	"credential\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12&\n" +
	"\x0fpeer_network_id\x18\x03 \x01(\tR\rpeerNetworkId\"\x1b\n" +
	"\x19AuthorizePeerPairResponse\"\x17\n" +
	"\x15GetTrustBundleRequest\"o\n" +
	"\x16GetTrustBundleResponse\x12U\n" +
	"\x12relay_trust_bundle\x18\x01 \x01(\v2'.endlessnet.relay.v1.SigningTrustBundleR\x10relayTrustBundle2\xef\x02\n" +
	"\x14RelayUpstreamService\x12x\n" +
	"\x13AuthorizeCredential\x12/.endlessnet.relay.v1.AuthorizeCredentialRequest\x1a0.endlessnet.relay.v1.AuthorizeCredentialResponse\x12r\n" +
	"\x11AuthorizePeerPair\x12-.endlessnet.relay.v1.AuthorizePeerPairRequest\x1a..endlessnet.relay.v1.AuthorizePeerPairResponse\x12i\n" +
	"\x0eGetTrustBundle\x12*.endlessnet.relay.v1.GetTrustBundleRequest\x1a+.endlessnet.relay.v1.GetTrustBundleResponseB3Z1github.com/endless-net/relay/api/relay/v1;relayv1b\x06proto3"

var (
	file_api_relay_v1_upstream_proto_rawDescOnce sync.Once
	file_api_relay_v1_upstream_proto_rawDescData []byte
)

func file_api_relay_v1_upstream_proto_rawDescGZIP() []byte {
	file_api_relay_v1_upstream_proto_rawDescOnce.Do(func() {
		file_api_relay_v1_upstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_relay_v1_upstream_proto_rawDesc), len(file_api_relay_v1_upstream_proto_rawDesc)))
	})
	return file_api_relay_v1_upstream_proto_rawDescData
}

var file_api_relay_v1_upstream_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_relay_v1_upstream_proto_goTypes = []any{
	(*AuthorizeCredentialRequest)(nil),  // 0: endlessnet.relay.v1.AuthorizeCredentialRequest
	(*AuthorizeCredentialResponse)(nil), // 1: endlessnet.relay.v1.AuthorizeCredentialResponse
	(*AuthorizePeerPairRequest)(nil),    // 2: endlessnet.relay.v1.AuthorizePeerPairRequest
	(*AuthorizePeerPairResponse)(nil),   // 3: endlessnet.relay.v1.AuthorizePeerPairResponse
	(*GetTrustBundleRequest)(nil),       // 4: endlessnet.relay.v1.GetTrustBundleRequest
	(*GetTrustBundleResponse)(nil),      // 5: endlessnet.relay.v1.GetTrustBundleResponse
	(*Credential)(nil),                  // 6: endlessnet.relay.v1.Credential
	(*SigningTrustBundle)(nil),          // 7: endlessnet.relay.v1.SigningTrustBundle
}
var file_api_relay_v1_upstream_proto_depIdxs = []int32{
	6, // 0: endlessnet.relay.v1.AuthorizeCredentialRequest.credential:type_name -> endlessnet.relay.v1.Credential
	6, // 1: endlessnet.relay.v1.AuthorizePeerPairRequest.credential:type_name -> endlessnet.relay.v1.Credential
	7, // 2: endlessnet.relay.v1.GetTrustBundleResponse.relay_trust_bundle:type_name -> endlessnet.relay.v1.SigningTrustBundle
	0, // 3: endlessnet.relay.v1.RelayUpstreamService.AuthorizeCredential:input_type -> endlessnet.relay.v1.AuthorizeCredentialRequest
	2, // 4: endlessnet.relay.v1.RelayUpstreamService.AuthorizePeerPair:input_type -> endlessnet.relay.v1.AuthorizePeerPairRequest
	4, // 5: endlessnet.relay.v1.RelayUpstreamService.GetTrustBundle:input_type -> endlessnet.relay.v1.GetTrustBundleRequest
	1, // 6: endlessnet.relay.v1.RelayUpstreamService.AuthorizeCredential:output_type -> endlessnet.relay.v1.AuthorizeCredentialResponse
	3, // 7: endlessnet.relay.v1.RelayUpstreamService.AuthorizePeerPair:output_type -> endlessnet.relay.v1.AuthorizePeerPairResponse
	5, // 8: endlessnet.relay.v1.RelayUpstreamService.GetTrustBundle:output_type -> endlessnet.relay.v1.GetTrustBundleResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_relay_v1_upstream_proto_init() }
func file_api_relay_v1_upstream_proto_init() {
	if File_api_relay_v1_upstream_proto != nil {
		return
	}
	file_api_relay_v1_relay_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_relay_v1_upstream_proto_rawDesc), len(file_api_relay_v1_upstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_relay_v1_upstream_proto_goTypes,
		DependencyIndexes: file_api_relay_v1_upstream_proto_depIdxs,
		MessageInfos:      file_api_relay_v1_upstream_proto_msgTypes,
	}.Build()
	File_api_relay_v1_upstream_proto = out.File
	file_api_relay_v1_upstream_proto_goTypes = nil
	file_api_relay_v1_upstream_proto_depIdxs = nil
}
